# Generated by Django 2.1.5 on 2019-01-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='email',
            field=models.TextField(default='joedoe@weber.edu', max_length=250),
            preserve_default=False,
        ),
    ]
